export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_LOGOUT = 'LOGIN_USER_LOGOUT';

export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';

export const FOOD_FETCH_START = "FOOD_FETCH_START";
export const FOOD_FETCH_ERROR = "FOOD_FETCH_ERROR";
export const FOOD_FETCH_SUCCESS = "FOOD_FETCH_SUCCESS";

export const DRINK_FETCH_START = "DRINK_FETCH_START";
export const DRINK_FETCH_ERROR = "DRINK_FETCH_ERROR";
export const DRINK_FETCH_SUCCESS = "DRINK_FETCH_SUCCESS";
