// AUTH
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_LOGOUT = 'LOGIN_USER_LOGOUT';

export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';

// PRODUCT
export const FOOD_FETCH_START = "FOOD_FETCH_START";
export const FOOD_FETCH_ERROR = "FOOD_FETCH_ERROR";
export const FOOD_FETCH_SUCCESS = "FOOD_FETCH_SUCCESS";

export const DRINK_FETCH_START = "DRINK_FETCH_START";
export const DRINK_FETCH_ERROR = "DRINK_FETCH_ERROR";
export const DRINK_FETCH_SUCCESS = "DRINK_FETCH_SUCCESS";

// ORDER
export const ORDER_FETCH_START = "ORDER_FETCH_START";
export const ORDER_FETCH_SUCCESS = "ORDER_FETCH_SUCCESS";
export const ORDER_FETCH_ERROR = "ORDER_FETCH_ERROR";

export const ORDER_NEW_START = "ORDER_NEW_START";
export const ORDER_NEW_SUCCESS = "ORDER_NEW_SUCCESS";
export const ORDER_NEW_ERROR = "ORDER_NEW_ERROR";

export const ORDER_UPDATE_START = "ORDER_UPDATE_START";
export const ORDER_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS";
export const ORDER_UPDATE_ERROR = "ORDER_UPDATE_ERROR";

export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const INRECREMENT_PRODUCT = "INRECREMENT_PRODUCT";
export const DECREMENT_PRODUCT = "DECREMENT_PRODUCT";

// INGREDIENT
export const INGREDIENT_FETCH_START = "INGREDIENT_FETCH_START";
export const INGREDIENT_FETCH_SUCCESS = "INGREDIENT_FETCH_SUCCESS";
export const INGREDIENT_FETCH_ERROR = "INGREDIENT_FETCH_ERROR";
